dependencies:
- name: amdocs-ws-api
  repository: https://chartmuseum.jx.build.melita.it
  version: 0.3.321
- name: appointment-scheduling-api
  repository: https://chartmuseum.jx.build.melita.it
  version: 1.0.42
- name: customer-360-frontend
  repository: https://chartmuseum.jx.build.melita.it
  version: 0.0.13
- name: eshop-product-api
  repository: https://chartmuseum.jx.build.melita.it
  version: 1.0.57
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: kyc-service-api
  repository: https://chartmuseum.jx.build.melita.it
  version: 1.0.35
- name: melita-it-eshop-api
  repository: https://chartmuseum.jx.build.melita.it
  version: 1.0.123
- name: melita-it-eshop-frontend
  repository: https://chartmuseum.jx.build.melita.it
  version: 0.0.133
- name: openfiber-address-api
  repository: https://chartmuseum.jx.build.melita.it
  version: 1.0.59
- name: ott-service-api
  repository: https://chartmuseum.jx.build.melita.it
  version: 1.0.47
- name: payment-service-api
  repository: https://chartmuseum.jx.build.melita.it
  version: 1.3.2
- name: personal-details-validator-api
  repository: https://chartmuseum.jx.build.melita.it
  version: 1.0.48
- name: sandbox
  repository: https://chartmuseum.jx.build.melita.it
  version: 0.0.80
- name: selfcare-api
  repository: https://chartmuseum.jx.build.melita.it
  version: 3.50.84
- name: mymelita-frontend
  repository: https://chartmuseum.jx.build.melita.it
  version: 0.0.28
- name: mesh-api
  repository: https://chartmuseum.jx.build.melita.it
  version: 1.3.0
- name: modeminfo-api
  repository: https://chartmuseum.jx.build.melita.it
  version: 1.13.1
