dependencies:
- name: amdocs-ws-api
  repository: https://chartmuseum.jx.build.melita.it
  version: 0.3.381
- name: appointment-scheduling-api
  repository: https://chartmuseum.jx.build.melita.it
  version: 1.0.46
- name: customer-360-frontend
  repository: https://chartmuseum.jx.build.melita.it
  version: 0.0.32
- name: eshop-product-api
  repository: https://chartmuseum.jx.build.melita.it
  version: 1.0.57
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: kyc-service-api
  repository: https://chartmuseum.jx.build.melita.it
  version: 1.0.38
- name: melita-it-eshop-api
  repository: https://chartmuseum.jx.build.melita.it
  version: 1.0.139
- name: melita-it-eshop-frontend
  repository: https://chartmuseum.jx.build.melita.it
  version: 0.0.133
- name: openfiber-address-api
  repository: https://chartmuseum.jx.build.melita.it
  version: 1.0.63
- name: ott-service-api
  repository: https://chartmuseum.jx.build.melita.it
  version: 1.0.50
- name: payment-service-api
  repository: https://chartmuseum.jx.build.melita.it
  version: 1.3.4
- name: personal-details-validator-api
  repository: https://chartmuseum.jx.build.melita.it
  version: 1.0.53
- name: sandbox
  repository: https://chartmuseum.jx.build.melita.it
  version: 0.0.80
- name: selfcare-api
  repository: https://chartmuseum.jx.build.melita.it
  version: 3.50.134
- name: mymelita-frontend
  repository: https://chartmuseum.jx.build.melita.it
  version: 0.0.41
- name: mesh-api
  repository: https://chartmuseum.jx.build.melita.it
  version: 1.3.0
- name: modeminfo-api
  repository: https://chartmuseum.jx.build.melita.it
  version: 1.13.23
- name: customer-events-ws
  repository: https://chartmuseum.jx.build.melita.it
  version: 1.0.4
