dependencies:
- name: amdocs-ws-api
  repository: https://chartmuseum.jx.build.melita.it
  version: 0.4.26
- name: appointment-scheduling-api
  repository: https://chartmuseum.jx.build.melita.it
  version: 1.0.51
- name: customer-360-frontend
  repository: https://chartmuseum.jx.build.melita.it
  version: 0.0.45
- name: eshop-product-api
  repository: https://chartmuseum.jx.build.melita.it
  version: 1.0.59
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: kyc-service-api
  repository: https://chartmuseum.jx.build.melita.it
  version: 1.0.38
- name: melita-it-eshop-api
  repository: https://chartmuseum.jx.build.melita.it
  version: 1.0.150
- name: melita-it-eshop-frontend
  repository: https://chartmuseum.jx.build.melita.it
  version: 0.0.140
- name: openfiber-address-api
  repository: https://chartmuseum.jx.build.melita.it
  version: 1.0.67
- name: ott-service-api
  repository: https://chartmuseum.jx.build.melita.it
  version: 1.0.51
- name: payment-service-api
  repository: https://chartmuseum.jx.build.melita.it
  version: 1.3.19
- name: personal-details-validator-api
  repository: https://chartmuseum.jx.build.melita.it
  version: 1.0.54
- name: sandbox
  repository: https://chartmuseum.jx.build.melita.it
  version: 0.0.83
- name: selfcare-api
  repository: https://chartmuseum.jx.build.melita.it
  version: 3.50.171
- name: mymelita-frontend
  repository: https://chartmuseum.jx.build.melita.it
  version: 0.0.58
- name: mesh-api
  repository: https://chartmuseum.jx.build.melita.it
  version: 1.3.2
- name: modeminfo-api
  repository: https://chartmuseum.jx.build.melita.it
  version: 1.13.23
- name: customer-events-ws
  repository: https://chartmuseum.jx.build.melita.it
  version: 1.0.14
- name: melita-it-customer-management-api
  repository: https://chartmuseum.jx.build.melita.it
  version: 1.0.21
