dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: jx-melita-it-eshop-frontend
  repository: https://chartmuseum.jx.build.melita.it
  version: 0.0.62
- alias: melita-it-eshop-frontend
  name: melita-it-eshop-frontend
  repository: https://chartmuseum.jx.build.melita.it
  version: 0.0.62
- name: sandbox
  repository: https://chartmuseum.jx.build.melita.it
  version: 0.0.46
