PipelineSecrets: {}
cleanup:
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --cleanup
controllerbuild: {}
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --v
  - 4
  config:
    domain: build.melita.it
    exposer: Ingress
    http: "true"
jenkins:
  Servers:
    Global: {}
prow: {}
sandbox:
  replicaCount: 1
amdocs-ws-api:
  replicaCount: 3
  springBoot:
    profiles: default,gcp,ita-production
payment-service-api:
  env:
    STATUS_URL: https://www.staging.melita.it/api/payment/apco/checkout/callback
  springBoot:
    databaseInstance: melita-italy-staging:europe-west2:staging-mysql=tcp:3306
selfcare-api:
  replicaCount: 3
  springBoot:
    databaseInstance: melita-italy-staging:europe-west2:staging-mysql=tcp:3306
    profiles: default,gcp,gcp-staging,default,amdocs-ws-api-production,ehcache,all-diagnostics,wifi-diagnostics,antivirus,selfcare-instance-italia,test,ad-italia,amdocs-rest-spring4,ws-api-production
